name: Verify
on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Lint code
        run: pnpm format && pnpm lint
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: 'chore: format'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'

  types:
    name: Types
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        
      - name: Check types
        run: pnpm typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: ['bun', 'deno', 'node-16', 'node-18', 'node-20', 'node-latest', 'next', 'vite']
        include:
          - type: bun
            script: bun
          - type: deno
            script: deno
          - type: node-16
            node-version: 16
            script: node
          - type: node-18
            node-version: 18
            script: node
          - type: node-20
            node-version: 20
            script: node
          - type: node-latest
            node-version: latest
            script: node
          - type: next
            script: next
          - type: vite
            script: vite

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Bun
        if: ${{ matrix.script == 'bun' }}
        uses: oven-sh/setup-bun@v1

      - name: Set up Node
        if: ${{ matrix.script == 'node' }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Deno
        if: ${{ matrix.script == 'deno' }}
        uses: denoland/setup-deno@v1

      - name: Install Playwright Browsers
        if: ${{ matrix.script == 'next' || matrix.script == 'vite' }}
        run: npx playwright install --with-deps

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build
        run: pnpm build

      - name: Run tests
        run: pnpm test:${{ matrix.script }}